// api endpoint
export const FLAG_GETTING_API_ENDPOINT = 'FLAG_GETTING_API_ENDPOINT';
export const GET_API_ENDPOINT_SUCCEEDED = 'GET_API_ENDPOINT_SUCCEEDED';
export const GET_API_ENDPOINT_FAILED = 'GET_API_ENDPOINT_FAILED';

// settings
export const FLAG_GETTING_SETTINGS = 'FLAG_GETTING_SETTINGS';
export const GET_SETTINGS_SUCCEEDED = 'GET_SETTINGS_SUCCEEDED';
export const GET_SETTINGS_FAILED = 'GET_SETTINGS_FAILED';
export const OPEN_SETTINGS = 'OPEN_SETTINGS';
export const CLOSE_SETTINGS = 'CLOSE_SETTINGS';
export const SET_HEADER_VISIBILITY = 'SET_HEADER_VISIBILITY';
export const SET_BADGE_GROUP = 'SET_BADGE_GROUP';
